language: php

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6
 - 7.0

matrix:
   allow_failures:
   - php: 5.6 # travis seems to fail on adding activity - doesn't fail when running behat locally.

env:
 matrix:
    - DB=pgsql MOODLE_BRANCH=master TASK=FULL
    - DB=mysqli MOODLE_BRANCH=master TASK=LIMITED

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

before_script:
  # disable xdebug to speed up php 7.0 tests.
    - phpenv config-rm xdebug.ini

script:
    - >
      if [ "$TASK" = 'FULL' ];
      then
          moodle-plugin-ci phplint
          moodle-plugin-ci phpcpd
          moodle-plugin-ci phpmd
          moodle-plugin-ci codechecker
          moodle-plugin-ci csslint
          moodle-plugin-ci shifter
          moodle-plugin-ci jshint
          moodle-plugin-ci validate
          moodle-plugin-ci phpunit
          moodle-plugin-ci behat
      fi
    - >
      if [ "$TASK" = 'LIMITED' ];
      then
         moodle-plugin-ci phplint
         moodle-plugin-ci phpunit
         moodle-plugin-ci behat
      fi